version: '3.9'

networks:
  proxy:
    driver: bridge
    name: proxy

services:
  traefik:
    image: traefik:v2.5.6
    container_name: traefik
    restart: unless-stopped
    environment:
    - CF_API_EMAIL
    - CF_API_KEY
    ports:
    - 80:80
    - 443:443
    networks:
      proxy:
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./acme.json:/acme.json
    security_opt:
    - no-new-privileges:true
    command:
      # Traefik Providers
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      
      # HTTP Entry Points
      - --entryPoints.http.address=:80
      - --entryPoints.https.address=:443

      # Allow insecure behind Traefik
      - --serversTransport.insecureSkipVerify=true

      # Traefik Log File
      - --log.level=DEBUG
      - --log.filePath=/traefik.log
      - --log.format=common

      # Access Log
      - --accesslog.filepath=/access.log
      - --accesslog.format=common

      # Certificate Configuration
      - --certificatesResolvers.cloudflare.acme.storage=acme.json
      - --certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.cloudflare.acme.email=${CF_API_EMAIL}

      # Comment for production
      # - --certificatesResolvers.cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory

    labels:
      # Expose to Traefik.
      - traefik.enable=true

      # Expose Dashboard
      - traefik.http.routers.traefik-https.service=api@internal
      
      # Configure SSL certificates with Let's Encrypt.
      - traefik.http.routers.traefik-https.tls.domains[0].main=blakerenton.net
      - traefik.http.routers.traefik-https.tls.domains[0].sans=*.blakerenton.net

      # Configure HTTP endpoint, redirect to HTTPS.
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.blakerenton.net`)
      - traefik.http.routers.traefik.middlewares=traefik-https
      - traefik.http.middlewares.traefik-https.redirectscheme.scheme=https

      # Configure HTTPS endpoint.
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=Host(`traefik.blakerenton.net`)
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.tls.certResolver=cloudflare
