version: '3.9'

networks:
  web:
    name: web
    driver: bridge

services:
  nginx:
    image: nginx:1.21.5-alpine

    container_name: nginx

    restart: unless-stopped

    networks:
      web:

    labels:
      # Expose to Traefik.
      - traefik.enable=true

      # Configure HTTP endpoint, redirect to HTTPS.
      - traefik.http.routers.nginx.entrypoints=http
      - traefik.http.routers.nginx.rule=Host(`www.blakerenton.net`) || Host(`blakerenton.net`)
      - traefik.http.routers.nginx.middlewares=nginx-https
      - traefik.http.middlewares.nginx-https.redirectscheme.scheme=https

      # Configure HTTPS endpoint.
      - traefik.http.routers.nginx-https.entrypoints=https
      - traefik.http.routers.nginx-https.rule=Host(`www.blakerenton.net`) || Host(`blakerenton.net`)
      - traefik.http.routers.nginx-https.tls=true
      - traefik.http.routers.nginx-https.tls.certResolver=cloudflare
      