version: '3.9'

volumes:
  wordpress:
    name: wordpress_data
    driver: local

networks:
  web:
    external: true

services:
  wordpress:
    image: wordpress:5.8.3-php7.4-apache
    container_name: wordpress
    restart: unless-stopped
    networks:
      web:
    volumes:
    - wordpress:/var/www/html
    security_opt:
    - no-new-privileges:true
    environment:
    - WORDPRESS_DB_HOST 
    - WORDPRESS_DB_USER
    - WORDPRESS_DB_PASSWORD
    - WORDPRESS_DB_NAME
    - WORDPRESS_TABLE_PREFIX
    labels:
    # Expose to Traefik.
    - traefik.enable=true

    # Configure HTTP endpoint, redirect to HTTPS.
    - traefik.http.routers.wordpress.entrypoints=http
    - traefik.http.routers.wordpress.rule=Host(`blog.blakerenton.net`)
    - traefik.http.routers.wordpress.middlewares=traefik-https
    - traefik.http.middlewares.wordpress-https.redirectscheme.scheme=https

    # Configure HTTPS endpoint.
    - traefik.http.routers.wordpress-https.entrypoints=https
    - traefik.http.routers.wordpress-https.rule=Host(`blog.blakerenton.net`)
    - traefik.http.routers.wordpress-https.tls=true
    - traefik.http.routers.wordpress-https.tls.certResolver=cloudflare

