version: '3.9'

volumes:
  mariadb:
    name: mariadb_data
    driver: local

networks:
  web:
    external: true

services:
  mariadb:
    image: mariadb:10.7.1-focal
    container_name: mariadb
    restart: unless-stopped
    networks:
      web:
    volumes:
    - mariadb:/var/lib/mysql
    security_opt:
    - no-new-privileges:true
    environment:
    - MARIADB_ROOT_PASSWORD
    - MARIADB_DATABASE
    - MARIADB_USER
    - MARIADB_PASSWORD