version: '3.9'

volumes:
  ghost:
    external: true

networks:  
  web:
    name: web
    driver: bridge

services:
  ghost:
    image: ghost:alpine

    container_name: ghost

    restart: unless-stopped

    environment:
    - url=https://www.blakerenton.net

    volumes:
    - ghost:/var/lib/ghost/content

    networks:
      web:
      
    labels:
    - traefik.enable=true
    - traefik.http.routers.ghost.entrypoints=http
    - traefik.http.routers.ghost.rule=Host(`www.blakerenton.net`) || Host(`blakerenton.net`)
    - traefik.http.routers.ghost.middlewares=ghost-https
    - traefik.http.middlewares.ghost-https.redirectscheme.scheme=https

    # Configure HTTPS endpoint.
    - traefik.http.routers.ghost-https.entrypoints=https
    - traefik.http.routers.ghost-https.rule=Host(`www.blakerenton.net`) || Host(`blakerenton.net`)
    - traefik.http.routers.ghost-https.tls=true
    - traefik.http.routers.ghost-https.tls.certResolver=cloudflare
