version: '3.9'

volumes:
  uptime-kuma:
    name: uptimekuma_data
    driver: local

networks:
  web:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      web:
    volumes:
    - uptime-kuma:/app/data
    labels:
    # Expose to Traefik.
    - traefik.enable=true

    # Configure HTTP endpoint, redirect to HTTPS.
    - traefik.http.routers.status.entrypoints=http
    - traefik.http.routers.status.rule=Host(`status.blakerenton.net`)
    - traefik.http.routers.status.middlewares=status-https
    - traefik.http.middlewares.status-https.redirectscheme.scheme=https

    # Configure HTTPS endpoint.
    - traefik.http.routers.status-https.entrypoints=https
    - traefik.http.routers.status-https.rule=Host(`status.blakerenton.net`)
    - traefik.http.routers.status-https.tls=true
    - traefik.http.routers.status-https.tls.certResolver=cloudflare